# Generated by Django 2.2 on 2020-04-26 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0003_profilefeeditem_updated_on'),
    ]

    operations = [
        migrations.CreateModel(
            name='emptable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_id', models.IntegerField(default=0)),
                ('emp_firstname', models.CharField(max_length=255)),
                ('emp_lastname', models.CharField(max_length=255)),
                ('emp_active', models.BooleanField(default=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='profilefeeditem',
            name='updated_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
