# Generated by Django 2.2 on 2020-04-26 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0004_auto_20200426_1245'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeptTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dept_id', models.IntegerField(unique=True)),
                ('dept_name', models.CharField(max_length=255)),
                ('dept_active', models.BooleanField(default=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='emptable',
            name='emp_id',
            field=models.IntegerField(unique=True),
        ),
    ]
