# Generated by Django 2.2 on 2020-04-26 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0007_auto_20200426_1409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emptable',
            name='emp_dept',
            field=models.ForeignKey(default=12, on_delete=django.db.models.deletion.SET_DEFAULT, to='profiles_api.DeptTable'),
        ),
    ]
