# Generated by Django 2.2 on 2020-04-26 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0010_emptable_emp_dept'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='depttable',
            name='id',
        ),
        migrations.AlterField(
            model_name='depttable',
            name='dept_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
