# Generated by Django 2.2 on 2020-04-26 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0012_auto_20200426_1515'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emptable',
            name='emp_dept',
        ),
    ]
