# Generated by Django 2.2 on 2020-04-26 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0015_auto_20200426_1519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emptable',
            name='emp_dept',
            field=models.IntegerField(),
        ),
    ]
